#!/bin/bash




# notify-send --expire-time=3000 --icon=changes-allow "Bloqueando a Tela" "LockScreen rodando"
B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#f1f1f1cc'  # default
T='#FFFFFFFF'  # text
W='#73d216bb'  # wrong
V='#FFFFFFFF'  # verifying
p='#bca0dc' #
f="ComicSans:style=Bold"

PICTURE=/tmp/screen.png
~/.i3lockcolor/i3lock -i $PICTURE \
--insidevercolor=$C   \
--ringvercolor=$V     \
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
--insidecolor=$B      \
--ringcolor=$p        \
--linecolor=$B        \
--separatorcolor=$D   \
--verifcolor=$T        \
--wrongcolor=$T        \
--time-font=DejavuSansMono \
--date-font=DejavuSans:style=Bold \
--timecolor=$p        \
--datecolor=$p       \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
rm $PICTURE
