#!/bin/bash

shopt -s lastpipe
tmux list-panes | wc -l | read number
if [ $number -lt 2 ]; then
	tmux splitw -h -p 30 -c "#{pane_current_path}"
	tmux select-pane -L
fi
if [[ "$@" == *.py ]]; then 
	tmux send -t 2 'python3 '$@' | tee -a '$@'.log' Enter
else
	tmux send -t 2 './'$@' | tee -a '$@'.log' Enter
fi
